#ifndef DLLBITACORA_GLOBAL_H
#define DLLBITACORA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLBITACORA_LIBRARY)
#  define DLLBITACORA_EXPORT Q_DECL_EXPORT
#else
#  define DLLBITACORA_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLBITACORA_GLOBAL_H
